---
title: "Winter Paper Step-by-step"
author: "Peter King"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r Step Zero: Prepare Data}


## Start by converting raw "SurveyData.xlsx" to cleaned "Winter_dataframe_Step1.csv"
source("OtherScripts/Winter_CleanSurveyData.R")

## Add spatial data to make "Winter_dataframe_Step2.csv"
source("OtherScripts/Winter_AddSpatialData.R")



```


```{r Step One: Choice Models}


## Estimate basic attributes only model in WTP-space
source("CEModelScripts/Winter_MXL_ModelOne.R")

## Estimate basic attributes only model in preference-space
source("CEModelScripts/Winter_MXL_ModelOne_PrefSpace.R")

## Add covariates
source("CEModelScripts/Winter_MXL_ModelTwo.R")


## MUST RUN THIS FOR THE REST TO WORK:
source(here("OtherScripts","Winter_MergeSurveyAndWTP.R"))

```



```{r Step Two: Check WTP from the Choice Models Output}


## Check WTP distributions:
source(here("CEModelScripts","Winter_SarriasTests.R"))


## Calculate CS measures:
source(here("OtherScripts","Winter_ConsumerSurplus.R"))



```


```{r Step Two B: Plot WTP}


## Plot distribution of WTP
source(here("OtherScripts/Figures","Winter_Figure2_Boxplot_Unconditionals_Parellel.R"))


## Plot distribution of WTP by impairments
source(here("OtherScripts/Figures","Winter_Figure2_Impairments.R"))


## Plot distribution of WTP by visit frequency
source(here("OtherScripts/Figures","Winter_Figure2_VisitFrequency.R"))


```



```{r Step Three: Spatial Modelling}


## Global Moran's I for autocorrelation
source("OtherScripts/Spatial/Winter_GlobalMorans.R")

## Local Moran's I for autocorrelation
source(here("OtherScripts/Spatial","Winter_LocalMorans_Plots.R"))
source(here("OtherScripts/Spatial","Winter_LocalMorans_Table.R"))


## Spatial Lag Model simulate P values
source(here("OtherScripts/Spatial","Winter_SpatialLagModels_Simulator.R"))

## Spatial Lag Model all outputs
source(here("OtherScripts/Spatial","Winter_SpatialLagModels.R"))


```



```{r Step Four: Done}


# Now write the paper.

```

